# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/constraints/cadc_artys7.xdc

# Block Designs: bd/cadc_system/cadc_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system || ORIG_REF_NAME==cadc_system} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_clk_wiz_0_0/cadc_system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_clk_wiz_0_0 || ORIG_REF_NAME==cadc_system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_proc_sys_reset_0_0/cadc_system_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_proc_sys_reset_0_0 || ORIG_REF_NAME==cadc_system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_jtag_axi_0_0/cadc_system_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_jtag_axi_0_0 || ORIG_REF_NAME==cadc_system_jtag_axi_0_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_axi_interconnect_0_imp_xbar_0/cadc_system_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==cadc_system_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_axi_interconnect_0_0/cadc_system_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_axi_interconnect_0_0 || ORIG_REF_NAME==cadc_system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_axi_gpio_ps_0/cadc_system_axi_gpio_ps_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_axi_gpio_ps_0 || ORIG_REF_NAME==cadc_system_axi_gpio_ps_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_axi_gpio_qc_0/cadc_system_axi_gpio_qc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_axi_gpio_qc_0 || ORIG_REF_NAME==cadc_system_axi_gpio_qc_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_axi_gpio_tat_0/cadc_system_axi_gpio_tat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_axi_gpio_tat_0 || ORIG_REF_NAME==cadc_system_axi_gpio_tat_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_axi_gpio_analog_0/cadc_system_axi_gpio_analog_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_axi_gpio_analog_0 || ORIG_REF_NAME==cadc_system_axi_gpio_analog_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_axi_gpio_digital_0/cadc_system_axi_gpio_digital_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_axi_gpio_digital_0 || ORIG_REF_NAME==cadc_system_axi_gpio_digital_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_clock_divider_0_0/cadc_system_clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_clock_divider_0_0 || ORIG_REF_NAME==cadc_system_clock_divider_0_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_cadc_top_0_0/cadc_system_cadc_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_cadc_top_0_0 || ORIG_REF_NAME==cadc_system_cadc_top_0_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_ila_0_0/cadc_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_ila_0_0 || ORIG_REF_NAME==cadc_system_ila_0_0} -quiet] -quiet

# IP: bd/cadc_system/ip/cadc_system_util_vector_logic_0_0/cadc_system_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cadc_system_util_vector_logic_0_0 || ORIG_REF_NAME==cadc_system_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_artys7/cadc_artys7.gen/sources_1/bd/cadc_system/cadc_system_ooc.xdc
