# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.srcs/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/cadc_system_system_ila_0_0.xci
# IP: The module: 'cadc_system_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/bd_8dad.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad || ORIG_REF_NAME==bd_8dad} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_0/bd_8dad_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_ila_lib_0 || ORIG_REF_NAME==bd_8dad_ila_lib_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_1/bd_8dad_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_g_inst_0 || ORIG_REF_NAME==bd_8dad_g_inst_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_2/bd_8dad_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_0_aw_0 || ORIG_REF_NAME==bd_8dad_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_3/bd_8dad_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_0_w_0 || ORIG_REF_NAME==bd_8dad_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_4/bd_8dad_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_0_b_0 || ORIG_REF_NAME==bd_8dad_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_5/bd_8dad_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_0_ar_0 || ORIG_REF_NAME==bd_8dad_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_6/bd_8dad_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_0_r_0 || ORIG_REF_NAME==bd_8dad_slot_0_r_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_7/bd_8dad_slot_1_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_1_aw_0 || ORIG_REF_NAME==bd_8dad_slot_1_aw_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_8/bd_8dad_slot_1_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_1_w_0 || ORIG_REF_NAME==bd_8dad_slot_1_w_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_9/bd_8dad_slot_1_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_1_b_0 || ORIG_REF_NAME==bd_8dad_slot_1_b_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_10/bd_8dad_slot_1_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_1_ar_0 || ORIG_REF_NAME==bd_8dad_slot_1_ar_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_11/bd_8dad_slot_1_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_1_r_0 || ORIG_REF_NAME==bd_8dad_slot_1_r_0} -quiet] -quiet

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8dad_ila_lib_0 || ORIG_REF_NAME==bd_8dad_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8dad_ila_lib_0 || ORIG_REF_NAME==bd_8dad_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_0/bd_8dad_ila_lib_0_ooc.xdc

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/bd_8dad_ooc.xdc

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/cadc_system_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cadc_system_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.srcs/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/cadc_system_system_ila_0_0.xci
# IP: The module: 'cadc_system_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/bd_8dad.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad || ORIG_REF_NAME==bd_8dad} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_0/bd_8dad_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_ila_lib_0 || ORIG_REF_NAME==bd_8dad_ila_lib_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_1/bd_8dad_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_g_inst_0 || ORIG_REF_NAME==bd_8dad_g_inst_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_2/bd_8dad_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_0_aw_0 || ORIG_REF_NAME==bd_8dad_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_3/bd_8dad_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_0_w_0 || ORIG_REF_NAME==bd_8dad_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_4/bd_8dad_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_0_b_0 || ORIG_REF_NAME==bd_8dad_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_5/bd_8dad_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_0_ar_0 || ORIG_REF_NAME==bd_8dad_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_6/bd_8dad_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_0_r_0 || ORIG_REF_NAME==bd_8dad_slot_0_r_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_7/bd_8dad_slot_1_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_1_aw_0 || ORIG_REF_NAME==bd_8dad_slot_1_aw_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_8/bd_8dad_slot_1_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_1_w_0 || ORIG_REF_NAME==bd_8dad_slot_1_w_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_9/bd_8dad_slot_1_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_1_b_0 || ORIG_REF_NAME==bd_8dad_slot_1_b_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_10/bd_8dad_slot_1_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_1_ar_0 || ORIG_REF_NAME==bd_8dad_slot_1_ar_0} -quiet] -quiet

# IP: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_11/bd_8dad_slot_1_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8dad_slot_1_r_0 || ORIG_REF_NAME==bd_8dad_slot_1_r_0} -quiet] -quiet

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8dad_ila_lib_0 || ORIG_REF_NAME==bd_8dad_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8dad_ila_lib_0 || ORIG_REF_NAME==bd_8dad_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_0/bd_8dad_ila_lib_0_ooc.xdc

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/bd_8dad_ooc.xdc

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/cadc_system_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cadc_system_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
