# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_artys7/cadc_artys7.srcs/sources_1/bd/cadc_system/ip/cadc_system_jtag_axi_0_0/cadc_system_jtag_axi_0_0.xci
# IP: The module: 'cadc_system_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_artys7/cadc_artys7.gen/sources_1/bd/cadc_system/ip/cadc_system_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'cadc_system_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_artys7/cadc_artys7.gen/sources_1/bd/cadc_system/ip/cadc_system_jtag_axi_0_0/cadc_system_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cadc_system_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_artys7/cadc_artys7.srcs/sources_1/bd/cadc_system/ip/cadc_system_jtag_axi_0_0/cadc_system_jtag_axi_0_0.xci
# IP: The module: 'cadc_system_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_artys7/cadc_artys7.gen/sources_1/bd/cadc_system/ip/cadc_system_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'cadc_system_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_artys7/cadc_artys7.gen/sources_1/bd/cadc_system/ip/cadc_system_jtag_axi_0_0/cadc_system_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cadc_system_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
