set_property SRC_FILE_INFO {cfile:C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/constraints/cadc_artys7.xdc rfile:../../../../constraints/cadc_artys7.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F14   IOSTANDARD LVCMOS33 } [get_ports { sys_clk }]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G15   IOSTANDARD LVCMOS33 } [get_ports { sys_rst_n }]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_cadc_1p5mhz -source [get_pins cadc_system_i/clk_wiz_0/clk_out2] -divide_by 4 [get_pins cadc_system_i/clock_divider_0/U0/clk_reg_reg/Q]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -physically_exclusive -group [get_clocks -quiet clk_out1_cadc_system_clk_wiz_0_0] -group [get_clocks -quiet clk_out1_cadc_system_clk_wiz_0_0_1]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -physically_exclusive -group [get_clocks -quiet clk_out2_cadc_system_clk_wiz_0_0] -group [get_clocks -quiet clk_out2_cadc_system_clk_wiz_0_0_1]
