# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.runs/synth_1/cadc_system_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 4
set_param bd.open.in_stealth_mode 1
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s25csga225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.cache/wt [current_project]
set_property parent.project_path C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/hdl/cadc_system_wrapper.vhd
add_files C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.srcs/sources_1/bd/cadc_system/cadc_system.bd
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_clk_wiz_0_0/cadc_system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_clk_wiz_0_0/cadc_system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_clk_wiz_0_0/cadc_system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_proc_sys_reset_0_0/cadc_system_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_proc_sys_reset_0_0/cadc_system_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_1/bd_fda1_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_2/bd_fda1_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_3/bd_fda1_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_4/bd_fda1_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_5/bd_fda1_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_6/bd_fda1_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_7/bd_fda1_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_8/bd_fda1_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_9/bd_fda1_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_10/bd_fda1_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_11/bd_fda1_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_12/bd_fda1_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_13/bd_fda1_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_14/bd_fda1_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_15/bd_fda1_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_16/bd_fda1_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_20/bd_fda1_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_21/bd_fda1_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_22/bd_fda1_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_23/bd_fda1_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_24/bd_fda1_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_25/bd_fda1_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_26/bd_fda1_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_27/bd_fda1_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_28/bd_fda1_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_29/bd_fda1_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_30/bd_fda1_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_31/bd_fda1_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_33/bd_fda1_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_34/bd_fda1_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_35/bd_fda1_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_36/bd_fda1_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_37/bd_fda1_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_38/bd_fda1_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_40/bd_fda1_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_41/bd_fda1_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_42/bd_fda1_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_43/bd_fda1_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_44/bd_fda1_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_45/bd_fda1_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_47/bd_fda1_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_48/bd_fda1_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_49/bd_fda1_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_50/bd_fda1_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_51/bd_fda1_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_52/bd_fda1_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_54/bd_fda1_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_55/bd_fda1_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_56/bd_fda1_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_57/bd_fda1_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_58/bd_fda1_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_59/bd_fda1_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_61/bd_fda1_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_62/bd_fda1_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_63/bd_fda1_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_64/bd_fda1_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_65/bd_fda1_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_66/bd_fda1_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_68/bd_fda1_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_69/bd_fda1_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_70/bd_fda1_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_71/bd_fda1_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_72/bd_fda1_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_73/bd_fda1_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_75/bd_fda1_m07s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_76/bd_fda1_m07arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_77/bd_fda1_m07rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_78/bd_fda1_m07awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_79/bd_fda1_m07wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_80/bd_fda1_m07bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_82/bd_fda1_m08s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_83/bd_fda1_m08arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_84/bd_fda1_m08rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_85/bd_fda1_m08awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_86/bd_fda1_m08wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/bd_0/ip/ip_87/bd_fda1_m08bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_ps_0/cadc_system_axi_gpio_ps_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_ps_0/cadc_system_axi_gpio_ps_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_qc_0/cadc_system_axi_gpio_qc_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_qc_0/cadc_system_axi_gpio_qc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_tat_0/cadc_system_axi_gpio_tat_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_tat_0/cadc_system_axi_gpio_tat_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_analog_0/cadc_system_axi_gpio_analog_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_analog_0/cadc_system_axi_gpio_analog_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_digital_0/cadc_system_axi_gpio_digital_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_digital_0/cadc_system_axi_gpio_digital_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_out_0_0/cadc_system_axi_gpio_out_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_out_0_0/cadc_system_axi_gpio_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_out_1_0/cadc_system_axi_gpio_out_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_out_1_0/cadc_system_axi_gpio_out_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_out_2_0/cadc_system_axi_gpio_out_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_out_2_0/cadc_system_axi_gpio_out_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_out_3_0/cadc_system_axi_gpio_out_3_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_axi_gpio_out_3_0/cadc_system_axi_gpio_out_3_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/ip/ip_0/bd_8dad_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/bd_0/bd_8dad_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/ip/cadc_system_system_ila_0_0/cadc_system_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.gen/sources_1/bd/cadc_system/cadc_system_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/constraints/cadc_tile.xdc
set_property used_in_implementation false [get_files C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/constraints/cadc_tile.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/aptay/Dropbox/adiuvo/f14-CADC/implementation/vivado_proj_tile/cadc_tile.srcs/utils_1/imports/synth_1/cadc_system_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top cadc_system_wrapper -part xc7s25csga225-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cadc_system_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file cadc_system_wrapper_utilization_synth.rpt -pb cadc_system_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
